on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tf_module_branch:
        description: 'The branch where the Terraform module will be checked out from'
        required: false
        type: string
        default: 'main'

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency:
      group: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout main branch (for modules)
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tf_module_branch }}
          path: infra-module

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          cli_config_credentials_token: ${{ secrets.TFCLOUD_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve
