name: Terraform Lint

on:
  workflow_call:

env:
  TFLINT_VERSION: "v0.55.1"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout main branch (for modules)
        uses: actions/checkout@v4
        with:
          ref: main
          path: infra-module

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact
