name: Dev Branch Apply

on:
  push:
    branches:
      - dev
      - prod
    paths:
      - '*.tf'
      - '*.tfvars'
  # workflow_dispatch:
  #   inputs:
  #     target_branch:
  #       description: 'Target branch (for manual run)'
  #       required: true
  #       default: 'dev'

jobs:
  apply:
    uses: ./.github/workflows/terraform/_apply.yml
    with:
      environment: ${{ github.event_name == 'pull_request' && github.ref_name || inputs.target_branch }}
    secrets: inherit
