name: Dev and Prod branches PR checks

on:
  # pull_request:
  #   branches:
  #     - dev
  #     - prod
  #   paths:
  #     - '*.tf'
  #     - '*.tfvars'
  workflow_call:
    inputs:
      tf_module_branch:
        description: 'The branch where the Terraform module will be checked out from'
        required: false
        type: string
        default: 'main'
      pipeline_branch:
        description: 'The branch where the pipeline workflow will be reused from'
        required: false
        type: string
        default: 'main'

jobs:
  lint:
    uses: daleksandrowicz/terraform-modules-environments-tests/.github/workflows/_lint.yml@${{ inputs.pipeline_branch }}
    with:
      tf_module_branch: ${{ inputs.tf_module_branch }}

  security:
    uses: daleksandrowicz/terraform-modules-environments-tests/.github/workflows/_sec.yml@${{ inputs.pipeline_branch }}

  plan:
    needs: [lint, security]
    uses: daleksandrowicz/terraform-modules-environments-tests/.github/workflows/_plan.yml@${{ inputs.pipeline_branch }}
    permissions:
      contents: read
      pull-requests: write
    with:
      environment: ${{ github.event.pull_request.base.ref }}
      tf_module_branch: ${{ inputs.tf_module_branch }}
    secrets: inherit
