name: Dev Branch Apply

on:
  # push:
  #   branches:
  #     - dev
  #     - prod
  #   paths:
  #     - '*.tf'
  #     - '*.tfvars'
  workflow_call:
    inputs:
      tf_module_branch:
        description: 'The branch where the Terraform module will be checked out from'
        required: false
        type: string
        default: 'main'
      pipeline_branch:
        description: 'The branch where the pipeline workflow will be reused from'
        required: false
        type: string
        default: 'main'
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch (for manual run)'
        required: true
        default: 'dev'

jobs:
  apply:
    uses: daleksandrowicz/terraform-modules-environments-tests/.github/workflows/_apply.yml@${{ inputs.pipeline_branch }}
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && inputs.target_branch || github.ref_name }}
      tf_module_branch: ${{ inputs.tf_module_branch }}
    secrets: inherit
