name: Main branch PR checks

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.tf'
      - 'modules/**'
      - '.github/workflows/*.yml'

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml

  security:
    uses: ./.github/workflows/_sec.yml
