name: Dev and Prod branches PR checks

on:
  pull_request:
    branches:
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    uses: daleksandrowicz/terraform-modules-environments-tests/.github/workflows/dev-prod-pr.yml@feature/main
    # with:
    #   environment: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || inputs.target_branch }}
    secrets: inherit
