name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  apply:
    if: github.ref_name == 'dev' || github.ref_name == 'prod'
    uses: daleksandrowicz/terraform-modules-environments-tests/.github/workflows/_apply.yml@main
    with:
      environment: ${{ github.ref_name }}
      tf_module_branch: 'main'
    secrets: inherit