# name: Dev and Prod branches PR checks

# on:
#   push:
#     branches:
#       - dev

# permissions:
#   contents: read
#   pull-requests: write

# jobs:
#   apply:
#     uses: daleksandrowicz/terraform-modules-environments-tests/.github/workflows/_apply.yml@main
#     with:
#       environment: ${{ github.ref_name }}
#       tf_module_branch: 'main'
#     secrets: inherit
