name: Terraform Apply - Dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  apply:
    uses: daleksandrowicz/terraform-modules-environments-tests/.github/workflows/_apply.yml@main
    with:
      environment: ${{ github.ref_name }}
      tf_module_branch: 'main'
    secrets: inherit
